### ISSUE TITLE
Sendmail executable could not be found

### ISSUE THREAD

**Issue by cschwarck** [elestio-examples/nodebb#1]
When attempting to configure email with this image, I get the following:
"Error: The sendmail executable could not be found, please ensure it is installed and executable by the user running NodeBB."

Please consider adding this option to the image!

Thank you

**Comment by amitshuklabag** [comment]
Hey, 

We have investigated and fixed it by setting the user permission in our docker-compose. Please check now.

If you wish to try it on your existing deployed service, please go to the service details -> "Update Config" -> Docker Compose -> Add user:0:0 in nodebb -> "Update & Restart" to reflect it.

Also, in NodeBB, before sending an email for the test, you must save your changes.
