### ISSUE TITLE
wrong endpoint ./entrypoint.sh on arm

### ISSUE THREAD

**Issue by k1r0s** [elestio-examples/nodebb#2]
https://hub.docker.com/layers/elestio/nodebb/latest/images/sha256-ab226d5b0512b0d61855161a84f97d2300af742453c957422a500eaee745e42f?context=explore

zigor@DietPi:/$ docker run -d -p 4567:4567 --name forum elestio/nodebb
4820b1dd4d4a9278809fbde179e70b27093f8f2ec6f7377808f73373bdd2d45c
zigor@DietPi:/$ docker logs forum
/bin/sh: 1: ./entrypoint.sh: not found
2023-11-16T19:30:10.609Z [9] - info: Launching web installer on port 4567

**Comment by jbenguira** [comment]
Hey @k1r0s 
maybe you forgot to include the entrypoint.sh near your docker-compose file (https://github.com/elestio-examples/nodebb/blob/main/entrypoint.sh)
or you didn't mount it as a volume in the docker-compose? (https://github.com/elestio-examples/nodebb/blob/d2cddbee136dab7023bf0dbf0a1239e9015c81cd/docker-compose.yml#L16)

**Comment by k1r0s** [comment]
I just pulled the image from dockerhub and tried to run it raw :\ my bad
